### ISSUE TITLE
Fix timer incremental bug

### ISSUE THREAD

**Issue by Yonodactyl** [Yonodactyl/Bombus#28]
When you start the timer, everything is fine. However, if the timer is running and you try to start the timer again, the function fires as many times as you tap. This means that the timer can be reduced by 20 seconds a second if you tap it enough.

This is a bug, and is critical for the use of the app. We must clean the code up to make something better.

**Comment by Yonodactyl** [comment]
For now the start timer button is static; however, a feature that I think (and we can discuss further) is that the "Start Timer" should change to "Pause Timer" once the countdown has begun. Once you press the pause timer button you should see the timer stop the countdown.

A very early implementation I thought for this would be to store the current `Double` [value](https://github.com/Yonodactyl/Bombus/blob/6f0128fd4486b84ba7fba921d9edcbb82f1ec0ae/Bombus/ViewModel/SessionView%2BModel.swift#L20) of the timer in a temp variable, and then call a function to [invalidate the timer](https://github.com/Yonodactyl/Bombus/blob/6f0128fd4486b84ba7fba921d9edcbb82f1ec0ae/Bombus/ViewModel/SessionView%2BModel.swift#L32).

What are your thoughts on the functionality?

**Comment by musatrtr** [comment]
I think "Start Timer" and "Stop Timer" are ideal buttons. I did not well understand ViewModel class that we handle this method in but I know how to handle timer. I can fix this.
